### ISSUE TITLE
[Server] 개발환경 설정

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#4]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: express 서버 기본 설정 및 모듈 설치

### TODO
1. [x] express 서버 생성
2. [x] cors 연결 및 세부 설정
3. [x] 필요 모듈 설치 (상의 후 결정) 

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint1`
- Urgency: `High`
