### ISSUE TITLE
[Server] MySQL .env 파일 설정

### ISSUE THREAD

**Issue by james-taeil** [codestates/AllAboutMe#57]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail:  DB USERNAME/PASSWORD/DATABASE_NAME/ACCESS_SECRET 만들기

### TODO
1. [x] DB USERNAME 확인
2. [x] DB PASSWORD 확인
3. [x] DATABASE_NAME 확인
4. [x] ACCESS_SECRET 확인

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint2`
- Urgency: `High`
