### ISSUE TITLE
[Server] Post - 글 목록 불러오기

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#61]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: Post의 모든 글 목록 불러오기

### TODO
1. [ ] post controller에 글 목록 불러오기 기능 추가 
2. [ ] 추후 검색기능 추가 시 filter 고려 
3. [ ] api 요청 응답 테스트 

### Labels
- Estimated time: `E: 0.5h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
