### ISSUE TITLE
[Server] Post - 글 등록하기

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#66]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: Post 현재 사용자로 글 등록하기

### TODO
1. [ ] post controller에 글 작성 기능 추가
2. [ ] 작성자 아이디 현재 로그인 한 사용자로
3. [ ] api 요청 응답 테스트 

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `middle`
