### ISSUE TITLE
[Server] Post - 글 삭제 기능

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#69]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 글 삭제 기능 추가

### TODO
1. [ ] post controller에 글 삭제 추가
2. [ ] 작성자와 요청자가 일치하는 경우에만 기능 
3. [ ] api 요청 응답 테스트 

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `Middle`
