### ISSUE TITLE
[Server] 로그인 / 로그아웃 구현

### ISSUE THREAD

**Issue by james-taeil** [codestates/AllAboutMe#7]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: Login, Logout 기능 구현

### TODO
1. [x] POST 요청 로그인 구현
2. [x] POST 요청 로그아웃 구현
3. [x] DB Query 작성

### Labels
- Estimated time: `E: 3h`
- Group: `server`
- Sprint: `Sprint2`
- Urgency: `High`
