### ISSUE TITLE
[Server] Mypage - 내 정보 불러오기

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#79]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 내 정보 불러오기 기능 추가

### TODO
1. [x] user controller에 현재 로그인 사용자 정보 불러오기 기능 추가
2. [x] 요청자의 token 상태가 유효한 경우만
3. [x] api 요청 응답 테스트

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
