### ISSUE TITLE
[Server] Mypage - 내 글 불러오기

### ISSUE THREAD

**Issue by loverduck** [codestates/AllAboutMe#82]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 로그인 한 사용자 글만 불러오는 기능 추가

### TODO
1. [ ] user controller에 현재 로그인 사용자의 글 목록 불러오기 기능 추가
2. [ ] 요청자의 token 상태가 유효한 경우만
3. [ ] api 요청 응답 테스트

### Labels
- Estimated time: `E: 1h`
- Group: `server`
- Sprint: `Sprint3`
- Urgency: `High`
